shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 5
  - npm install --production
  - npm install tape
build: off
test_script: node --strong_mode --throw-deprecation --track-heap-objects test/test.js
cache: node_modules
